Service:
  name: "goproposal"
  path_prefix: "/goproposal"
  version: "1.0.0"
  debug: true
  port: 8080
Cache:
  enabled: false
  #duration for the data in cache
  expiration_minutes: 5
  #cleanup interval for expired items in cache
  purge_minutes: 10
Database:
  engine: "mocked"
  host: "localhost"
  name: ""
  port: 3306
  user: ""
  password: ""
